# Generated by Django 5.2.1 on 2025-05-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_parameters_default_parameter_set'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterSetBarrier',
        ),
    ]
