# Generated by Django 5.2.1 on 2025-05-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_delete_parametersetbarrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetwall',
            name='parameter_set',
        ),
        migrations.DeleteModel(
            name='ParameterSetGround',
        ),
        migrations.DeleteModel(
            name='ParameterSetWall',
        ),
    ]
