# Generated by Django 5.2.1 on 2025-05-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_remove_parametersetwall_parameter_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_animation_speed',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_bound_box_percent',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_move_speed',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_scale',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='cool_down_length',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='interaction_length',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='interaction_range',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='token_cents_value',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='tokens_per_period',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='world_height',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='world_width',
        ),
    ]
