# Generated by Django 5.2.1 on 2025-05-27 16:05

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_remove_parameterset_break_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='hex_color',
        ),
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='start_x',
        ),
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='start_y',
        ),
        migrations.CreateModel(
            name='ParameterSetGroupPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('values', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_groups', to='main.parametersetgroup')),
            ],
            options={
                'verbose_name': 'Parameter Set Group Period',
                'verbose_name_plural': 'Parameter Set Group Periods',
                'ordering': ['period_number'],
            },
        ),
    ]
