# Generated by Django 5.2.1 on 2025-05-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_parameterset_experiment_mode_parameterset_group_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='id_label',
        ),
    ]
