# Generated by Django 5.2.1 on 2025-05-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_parametersetplayer_group_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetgroupperiod',
            name='priority_scores',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='2,3,4,5'),
        ),
    ]
