# Generated by Django 5.2.1 on 2025-05-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_parametersetgroupperiod_player_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='max_priority_score',
            field=models.IntegerField(default=1, verbose_name='Max Priority Score'),
        ),
    ]
