# Generated by Django 5.2.1 on 2025-05-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_parameterset_max_priority_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='max_priority_score',
            field=models.IntegerField(default=10, verbose_name='Max Priority Score'),
        ),
    ]
