# Generated by Django 5.2.1 on 2025-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_sessionplayer_period_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='chat_gpt_mode',
            field=models.CharField(choices=[('Off', 'Off'), ('With_Context', 'With_Context'), ('Without_Context', 'Without_Context')], default='Off', max_length=20, verbose_name='ChatGPT Mode'),
        ),
    ]
