# Generated by Django 5.2.1 on 2025-06-04 17:34

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_parameterset_chat_gpt_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='chatgpt_prompt',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Chat GPT Prompt'),
        ),
    ]
