# Generated by Django 5.2.1 on 2025-06-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_sessionplayer_chatgpt_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionplayer',
            old_name='chatgpt_prompt',
            new_name='chat_gpt_prompt',
        ),
    ]
