# Generated by Django 5.2.2 on 2025-06-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_rename_chatgpt_prompt_sessionplayer_chat_gpt_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='chat_gpt_mode',
            field=models.CharField(choices=[('Off', 'Off'), ('With Context', 'With Context'), ('Without Context', 'Without Context')], default='Off', max_length=20, verbose_name='ChatGPT Mode'),
        ),
    ]
