# Generated by Django 5.2.2 on 2025-06-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_alter_parameterset_chat_gpt_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Session Event', 'verbose_name_plural': 'Session Events'},
        ),
        migrations.RemoveField(
            model_name='sessionevent',
            name='time_remaining',
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='group_number',
            field=models.IntegerField(default=0, verbose_name='Group Number'),
        ),
    ]
