# Generated by Django 5.2.2 on 2025-06-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_alter_sessionevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'ordering': ['timestamp'], 'verbose_name': 'Session Event', 'verbose_name_plural': 'Session Events'},
        ),
        migrations.AddField(
            model_name='parameterset',
            name='ready_to_go_on_length',
            field=models.IntegerField(default=30, verbose_name='Ready To Go On Length'),
        ),
    ]
