# Generated by Django 5.2.2 on 2025-06-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_alter_sessionevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionset',
            name='example_prize',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4, verbose_name='Example Prize'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='example_values',
            field=models.CharField(default='0.00,0.25,0.50,0.75', max_length=100, verbose_name='Example Values'),
        ),
    ]
