# Generated by Django 5.2.2 on 2025-07-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_instructionset_example_prize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='chat_gpt_length',
            field=models.IntegerField(default=60, verbose_name='ChatGPT Length'),
        ),
    ]
