# Generated by Django 5.2.2 on 2025-07-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_parameterset_chat_gpt_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionset',
            name='example_prize',
        ),
        migrations.AddField(
            model_name='instructionset',
            name='example_prize_index',
            field=models.IntegerField(default=0, verbose_name='Example Prize Index'),
        ),
    ]
