# Generated by Django 5.2.2 on 2025-07-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_remove_instructionset_example_prize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionset',
            name='example_priority_score',
            field=models.IntegerField(default=5, verbose_name='Example Priority Score'),
        ),
    ]
